CREATE TABLE IF NOT EXISTS FOO (
    IDT_FOO SERIAL PRIMARY KEY,
    DES_TITLE VARCHAR(255) NOT NULL,
    DES_DESCRIPTION VARCHAR(255),
    IND_STATUS VARCHAR(255) NOT NULL,
    DAT_CREATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DAT_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
